### ISSUE TITLE
 Forge breaks your mod.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [CodenameRevy/Additional-Bars#1]
Forge 1.15.1 - 20.0.51 Changlog "Rename ModConfigEvent.ConfigReloading to ModConfigEvent.Reloading"

Breaks your mod. Please update. Thanks.

**Comment by CodenameRevy** [comment]
Will look into it. Also, I hope you made a typo with forge version, because 1.15.1 is Forge version 30...

**Comment by CodenameRevy** [comment]
Fixed in version 1.1.1
