### ISSUE TITLE
[1.15.2] add zh_tw.json file

### ISSUE THREAD

**Issue by fantasyair18** [CodenameRevy/Additional-Bars#3]
{
  "block.additionalbars.gold_bars": "金欄杆",
  "block.additionalbars.acacia_bars": "相思木欄杆",
  "block.additionalbars.birch_bars": "樺木欄杆",
  "block.additionalbars.dark_oak_bars": "黑橡木欄杆",
  "block.additionalbars.jungle_bars": "叢林木欄杆",
  "block.additionalbars.oak_bars": "橡木欄杆",
  "block.additionalbars.spruce_bars": "杉木欄杆",

  "block.additionalbars.crossed_iron_bars": "鐵欄杆(交叉)",
  "block.additionalbars.crossed_gold_bars": "金欄杆(交叉)",
  "block.additionalbars.crossed_acacia_bars": "相思木欄杆(交叉)",
  "block.additionalbars.crossed_birch_bars": "樺木欄杆(交叉)",
  "block.additionalbars.crossed_dark_oak_bars": "黑橡木欄杆(交叉)",
  "block.additionalbars.crossed_jungle_bars": "叢林木欄杆(交叉)",
  "block.additionalbars.crossed_oak_bars": "橡木欄杆(交叉)",
  "block.additionalbars.crossed_spruce_bars": "杉木欄杆(交叉)",

  "block.additionalbars.fir_bars": "冷杉木欄杆",
  "block.additionalbars.redwood_bars": "紅木欄杆",
  "block.additionalbars.cherry_bars": "櫻花木欄杆",
  "block.additionalbars.mahogany_bars": "桃花心木欄杆",
  "block.additionalbars.jacaranda_bars": "藍花楹木欄杆",
  "block.additionalbars.palm_bars": "棕櫚木欄杆",
  "block.additionalbars.willow_bars": "柳木欄杆",
  "block.additionalbars.dead_bars": "垂死木欄杆",
  "block.additionalbars.magic_bars": "魔法木欄杆",
  "block.additionalbars.umbran_bars": "暗影木欄杆",
  "block.additionalbars.hellbark_bars": "地獄皮木欄杆",

  "block.additionalbars.crossed_fir_bars": "冷杉木欄杆(交叉)",
  "block.additionalbars.crossed_redwood_bars": "紅木欄杆(交叉)",
  "block.additionalbars.crossed_cherry_bars": "櫻花木欄杆(交叉)",
  "block.additionalbars.crossed_mahogany_bars": "桃花心木欄杆(交叉)",
  "block.additionalbars.crossed_jacaranda_bars": "藍花楹木欄杆(交叉)",
  "block.additionalbars.crossed_palm_bars": "棕櫚木欄杆(交叉)",
  "block.additionalbars.crossed_willow_bars": "柳木欄杆(交叉)",
  "block.additionalbars.crossed_dead_bars": "垂死木欄杆(交叉)",
  "block.additionalbars.crossed_magic_bars": "魔法木欄杆(交叉)",
  "block.additionalbars.crossed_umbran_bars": "暗影木欄杆(交叉)",
  "block.additionalbars.crossed_hellbark_bars": "地獄皮木欄杆(交叉)",

  "itemGroup.additionalBars": "Additional Bars"
}

**Comment by CodenameRevy** [comment]
It will be added in the next update, but next time please submit a pull request. Thanks!
